collections:
  # Install a collection from Ansible Galaxy.
  - name: community.docker
    source: https://galaxy.ansible.com
  # - name: community
  #   source: community.general
  - name: fortinet.fortios
    source: https://galaxy.ansible.com
  - name: cisco.meraki
    source: https://galaxy.ansible.com
